### ISSUE TITLE
is there a way to add vendor support ?

### ISSUE THREAD

**Issue by viktorblack** [julianperrott/WowClassicGrindBot#8]
is there anyway to add vendor support ?

**Comment by julianperrott** [comment]
To repair/vend stuff(e.g.) grays you would need to define where the vendor was, or have a list of all their locations. You would need the bot to path to the vendor, interact with it, then go back to the grind path. This is all possible, but if I was going to do this then I would want to change the corpse run and vendor pathing to work out their own paths rather than use a pre-defined one. So it is a good idea, perhaps I will do it.

**Comment by viktorblack** [comment]
that would be so nice

**Comment by julianperrott** [comment]
Pathing added to the bot, so it can now path to outside vendors added, see Readme.
